// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADZx4zRveKQLg_ho1RBkGIp-L0xqXDpuM',
    appId: '1:417559432644:web:9dfcd7fceb260d4ecf6891',
    messagingSenderId: '417559432644',
    projectId: 'cprujobapp',
    authDomain: 'cprujobapp.firebaseapp.com',
    storageBucket: 'cprujobapp.firebasestorage.app',
    measurementId: 'G-9HS6ZY2G0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxTEWDD3iKYzYeLY7_L0cIuUcbrebKhbk',
    appId: '1:417559432644:android:1defc30ef5c72ed8cf6891',
    messagingSenderId: '417559432644',
    projectId: 'cprujobapp',
    storageBucket: 'cprujobapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXTHMuzSDekI1jznso5iMF36pc1nc5_4I',
    appId: '1:417559432644:ios:801dbb8a8adc4ea9cf6891',
    messagingSenderId: '417559432644',
    projectId: 'cprujobapp',
    storageBucket: 'cprujobapp.firebasestorage.app',
    iosBundleId: 'com.example.cprujobapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXTHMuzSDekI1jznso5iMF36pc1nc5_4I',
    appId: '1:417559432644:ios:801dbb8a8adc4ea9cf6891',
    messagingSenderId: '417559432644',
    projectId: 'cprujobapp',
    storageBucket: 'cprujobapp.firebasestorage.app',
    iosBundleId: 'com.example.cprujobapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADZx4zRveKQLg_ho1RBkGIp-L0xqXDpuM',
    appId: '1:417559432644:web:d82b5e12463e2879cf6891',
    messagingSenderId: '417559432644',
    projectId: 'cprujobapp',
    authDomain: 'cprujobapp.firebaseapp.com',
    storageBucket: 'cprujobapp.firebasestorage.app',
    measurementId: 'G-M427HCTMBK',
  );
}
